### ISSUE TITLE
[Security] Workflow CI.yml is using vulnerable action actions/checkout

### ISSUE THREAD

**Issue by Freakston** [NREL/REoptLite#60]
The workflow CI.yml is referencing action actions/checkout using references v1.0.0. However this reference is missing the commit [a6747255bd19d7a757dbdda8c654a9f84db19839](https://github.com/actions/checkout/commits/a6747255bd19d7a757dbdda8c654a9f84db19839) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by NLaws** [comment]
@Freakston is there a remedy for this issue?

**Comment by Freakston** [comment]
@NLaws you can fix this by bumping up the actions checkout version.(v2)

**Comment by NLaws** [comment]
@Freakston we are already at v2 (https://github.com/NREL/REoptLite/blob/378d165c53e5728a694dab063549bccad4b94af8/.github/workflows/CI.yml#L15)

**Comment by Freakston** [comment]
@NLaws Sorry about the report it was created by an automated tool. Thanks for the information.
